export const LOGIN_USER = 'LOGIN_USER'
export const SIGNUP_USER = 'SIGNUP_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const SET_NOTES = 'SET_NOTES'
export const ADD_NOTE = 'ADD_NOTE'
export const EDIT_NOTE = 'EDIT_NOTE'
export const DELETE_NOTE = 'DELETE_NOTE'

export const GET_USERS = 'GET_USERS'

export const SET_USERS_FOLLOWED = 'SET_USERS_FOLLOWED'
export const SET_FOLLOWERS = 'SET_FOLLOWERS'
export const REQUEST_FOLLOW_USER = 'REQUEST_FOLLOW_USER'
export const ACCEPT_FOLLOWER = 'ACCEPT_FOLLOWER'
export const DECLINE_FOLLOWER = 'DECLINE_FOLLOWER'